// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: server/modules/authentication/protos/authenticate_additional_args.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protos.V1 {

  /// <summary>Holder for reflection information generated from server/modules/authentication/protos/authenticate_additional_args.proto</summary>
  public static partial class AuthenticateAdditionalArgsReflection {

    #region Descriptor
    /// <summary>File descriptor for server/modules/authentication/protos/authenticate_additional_args.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AuthenticateAdditionalArgsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkdzZXJ2ZXIvbW9kdWxlcy9hdXRoZW50aWNhdGlvbi9wcm90b3MvYXV0aGVu",
            "dGljYXRlX2FkZGl0aW9uYWxfYXJncy5wcm90bxIJcHJvdG9zLnYxIjoKGkF1",
            "dGhlbnRpY2F0ZUFkZGl0aW9uYWxBcmdzEhwKFGNob3Nlbl9zZXJ2ZXJfcmVn",
            "aW9uGAEgASgJQldaVWdpdC50b3BmcmVlZ2FtZXMuY29tL3BhY2thZ2VzL3Vu",
            "aXR5LW1vZHVsZXMtZGVtby9zZXJ2ZXIvbW9kdWxlcy9hdXRoZW50aWNhdGlv",
            "bi9wcm90b3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.V1.AuthenticateAdditionalArgs), global::Protos.V1.AuthenticateAdditionalArgs.Parser, new[]{ "ChosenServerRegion" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Example additional arguments for the metagame.authenticationHandler.authenticate route request.
  /// </summary>
  public sealed partial class AuthenticateAdditionalArgs : pb::IMessage<AuthenticateAdditionalArgs> {
    private static readonly pb::MessageParser<AuthenticateAdditionalArgs> _parser = new pb::MessageParser<AuthenticateAdditionalArgs>(() => new AuthenticateAdditionalArgs());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AuthenticateAdditionalArgs> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.V1.AuthenticateAdditionalArgsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuthenticateAdditionalArgs() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuthenticateAdditionalArgs(AuthenticateAdditionalArgs other) : this() {
      chosenServerRegion_ = other.chosenServerRegion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuthenticateAdditionalArgs Clone() {
      return new AuthenticateAdditionalArgs(this);
    }

    /// <summary>Field number for the "chosen_server_region" field.</summary>
    public const int ChosenServerRegionFieldNumber = 1;
    private string chosenServerRegion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ChosenServerRegion {
      get { return chosenServerRegion_; }
      set {
        chosenServerRegion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AuthenticateAdditionalArgs);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AuthenticateAdditionalArgs other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChosenServerRegion != other.ChosenServerRegion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ChosenServerRegion.Length != 0) hash ^= ChosenServerRegion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ChosenServerRegion.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ChosenServerRegion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ChosenServerRegion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChosenServerRegion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AuthenticateAdditionalArgs other) {
      if (other == null) {
        return;
      }
      if (other.ChosenServerRegion.Length != 0) {
        ChosenServerRegion = other.ChosenServerRegion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ChosenServerRegion = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
