// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: server/modules/authentication/protos/create_account_additional_payload.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protos.V1 {

  /// <summary>Holder for reflection information generated from server/modules/authentication/protos/create_account_additional_payload.proto</summary>
  public static partial class CreateAccountAdditionalPayloadReflection {

    #region Descriptor
    /// <summary>File descriptor for server/modules/authentication/protos/create_account_additional_payload.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CreateAccountAdditionalPayloadReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkxzZXJ2ZXIvbW9kdWxlcy9hdXRoZW50aWNhdGlvbi9wcm90b3MvY3JlYXRl",
            "X2FjY291bnRfYWRkaXRpb25hbF9wYXlsb2FkLnByb3RvEglwcm90b3MudjEi",
            "OQoeQ3JlYXRlQWNjb3VudEFkZGl0aW9uYWxQYXlsb2FkEhcKD2N1c3RvbV9p",
            "dGVtX2lkcxgBIAMoCUJXWlVnaXQudG9wZnJlZWdhbWVzLmNvbS9wYWNrYWdl",
            "cy91bml0eS1tb2R1bGVzLWRlbW8vc2VydmVyL21vZHVsZXMvYXV0aGVudGlj",
            "YXRpb24vcHJvdG9zYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.V1.CreateAccountAdditionalPayload), global::Protos.V1.CreateAccountAdditionalPayload.Parser, new[]{ "CustomItemIds" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Example additional payload for the metagame.authenticationHandler.createAccount route response.
  /// </summary>
  public sealed partial class CreateAccountAdditionalPayload : pb::IMessage<CreateAccountAdditionalPayload> {
    private static readonly pb::MessageParser<CreateAccountAdditionalPayload> _parser = new pb::MessageParser<CreateAccountAdditionalPayload>(() => new CreateAccountAdditionalPayload());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateAccountAdditionalPayload> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.V1.CreateAccountAdditionalPayloadReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateAccountAdditionalPayload() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateAccountAdditionalPayload(CreateAccountAdditionalPayload other) : this() {
      customItemIds_ = other.customItemIds_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateAccountAdditionalPayload Clone() {
      return new CreateAccountAdditionalPayload(this);
    }

    /// <summary>Field number for the "custom_item_ids" field.</summary>
    public const int CustomItemIdsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_customItemIds_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> customItemIds_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> CustomItemIds {
      get { return customItemIds_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateAccountAdditionalPayload);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateAccountAdditionalPayload other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!customItemIds_.Equals(other.customItemIds_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= customItemIds_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      customItemIds_.WriteTo(output, _repeated_customItemIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += customItemIds_.CalculateSize(_repeated_customItemIds_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateAccountAdditionalPayload other) {
      if (other == null) {
        return;
      }
      customItemIds_.Add(other.customItemIds_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            customItemIds_.AddEntriesFrom(input, _repeated_customItemIds_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
