using System.Collections.Generic;
using UnityEngine.Scripting;
using Wildlife.Authentication;
using Wildlife.MetagameBase.Hooks;
using Protos.V1;
using System.Linq;
using Player = Wildlife.MetagameModuleAbstractions.Player;

// @todo Add comments here documenting the class

namespace Services.MetagameModules.Authentication
{
    public interface IAccountProvider
    {
        Player GetAccount();
        IEnumerable<string> GetCustomPayload();
    }

    public class AccountProvider : IAccountProvider
    {
        public const string ExampleNameArg = "Player123";

        private Player _player;
        private List<string> _customPayload;

        public AccountProvider(IAuthenticationHooksBuilder authHooksBuilder)
        {
            authHooksBuilder.AddCreateArgHook(new NoArgsHook(this, nameof(CreateArgsHook)));
            authHooksBuilder.AddAuthenticateArgHook(new SingleArgHook<Player>(this, nameof(AuthenticateArgsHook)));

            authHooksBuilder.AddAuthenticateHook(new Hook<Player>(this, nameof(OnAuthenticateResponse)));
            authHooksBuilder.AddCreateHook(new Hook<Player>(this, nameof(OnCreateResponse)));
        }

        public Player GetAccount()
        {
            return _player;
        }

        public IEnumerable<string> GetCustomPayload()
        {
            return _customPayload;
        }

        // Preserve must be kept for this method to avoid having this code stripped for some builds such as Android build.
        // Notice: CreateAccountAdditionalArgs is generated by the prototool based on an example proto. 
        // Please replace example protos by your own proto messages. These protos are located at ExampleProtos directory.
        [Preserve]
        public CreateAccountAdditionalArgs CreateArgsHook()
        {
            return new CreateAccountAdditionalArgs()
            {
                Name = ExampleNameArg,
                TutorialStep = 12,
                ChosenServerRegion = "us",
            };
        }

        // Preserve must be kept for this method to avoid having this code stripped for some builds such as Android build.
        // Notice: AuthenticateAdditionalArgs is generated by the prototool based on an example proto. 
        // Please replace example protos by your own proto messages. These protos are located at ExampleProtos directory.
        [Preserve]
        public AuthenticateAdditionalArgs AuthenticateArgsHook(Player player)
        {
            return new AuthenticateAdditionalArgs()
            {
                ChosenServerRegion = "eu",
            };
        }
        
        // Preserve must be kept for this method to avoid having this code stripped for some builds such as Android build.
        // Notice: AuthenticateAdditionalPayload is generated by the prototool based on an example proto. 
        // Please replace example protos by your own proto messages. These protos are located at ExampleProtos directory.
        [Preserve]
        public void OnAuthenticateResponse(Player player, AuthenticateAdditionalPayload additionalPayload)
        {
            _player = player;
            _customPayload = additionalPayload.CustomPlayerTags.ToList();
        }

        // Preserve must be kept for this method to avoid having this code stripped for some builds such as Android build.
        // Notice: CreateAccountAdditionalPayload is generated by the prototool based on an example proto. 
        // Please replace example protos by your own proto messages. These protos are located at ExampleProtos directory.
        [Preserve]
        public void OnCreateResponse(Player player, CreateAccountAdditionalPayload additionalPayload)
        {
            _player = player;
            _customPayload = additionalPayload.CustomPlayerTags.ToList();
        }
    }
}
