// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ExampleProtos/create_account_additional_payload.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protos.V1 {

  /// <summary>Holder for reflection information generated from ExampleProtos/create_account_additional_payload.proto</summary>
  public static partial class CreateAccountAdditionalPayloadReflection {

    #region Descriptor
    /// <summary>File descriptor for ExampleProtos/create_account_additional_payload.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CreateAccountAdditionalPayloadReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjVFeGFtcGxlUHJvdG9zL2NyZWF0ZV9hY2NvdW50X2FkZGl0aW9uYWxfcGF5",
            "bG9hZC5wcm90bxIJcHJvdG9zLnYxIjwKHkNyZWF0ZUFjY291bnRBZGRpdGlv",
            "bmFsUGF5bG9hZBIaChJjdXN0b21fcGxheWVyX3RhZ3MYASADKAlCSlpIZ2l0",
            "LnRvcGZyZWVnYW1lcy5jb20vcmluZy90ZW1wbGF0ZS9taW5pbWFsLWNsaWVu",
            "dC10ZW1wbGF0ZS9FeGFtcGxlUHJvdG9zYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.V1.CreateAccountAdditionalPayload), global::Protos.V1.CreateAccountAdditionalPayload.Parser, new[]{ "CustomPlayerTags" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Example additional payload for the metagame.authenticationHandler.createAccount route response.
  /// </summary>
  public sealed partial class CreateAccountAdditionalPayload : pb::IMessage<CreateAccountAdditionalPayload> {
    private static readonly pb::MessageParser<CreateAccountAdditionalPayload> _parser = new pb::MessageParser<CreateAccountAdditionalPayload>(() => new CreateAccountAdditionalPayload());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateAccountAdditionalPayload> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.V1.CreateAccountAdditionalPayloadReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateAccountAdditionalPayload() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateAccountAdditionalPayload(CreateAccountAdditionalPayload other) : this() {
      customPlayerTags_ = other.customPlayerTags_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateAccountAdditionalPayload Clone() {
      return new CreateAccountAdditionalPayload(this);
    }

    /// <summary>Field number for the "custom_player_tags" field.</summary>
    public const int CustomPlayerTagsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_customPlayerTags_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> customPlayerTags_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> CustomPlayerTags {
      get { return customPlayerTags_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateAccountAdditionalPayload);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateAccountAdditionalPayload other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!customPlayerTags_.Equals(other.customPlayerTags_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= customPlayerTags_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      customPlayerTags_.WriteTo(output, _repeated_customPlayerTags_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += customPlayerTags_.CalculateSize(_repeated_customPlayerTags_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateAccountAdditionalPayload other) {
      if (other == null) {
        return;
      }
      customPlayerTags_.Add(other.customPlayerTags_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            customPlayerTags_.AddEntriesFrom(input, _repeated_customPlayerTags_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
