// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: server/modules/authentication/protos/create_account_additional_args.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protos.V1 {

  /// <summary>Holder for reflection information generated from server/modules/authentication/protos/create_account_additional_args.proto</summary>
  public static partial class CreateAccountAdditionalArgsReflection {

    #region Descriptor
    /// <summary>File descriptor for server/modules/authentication/protos/create_account_additional_args.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CreateAccountAdditionalArgsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CklzZXJ2ZXIvbW9kdWxlcy9hdXRoZW50aWNhdGlvbi9wcm90b3MvY3JlYXRl",
            "X2FjY291bnRfYWRkaXRpb25hbF9hcmdzLnByb3RvEglwcm90b3MudjEiYAob",
            "Q3JlYXRlQWNjb3VudEFkZGl0aW9uYWxBcmdzEgwKBG5hbWUYASABKAkSFQoN",
            "dHV0b3JpYWxfc3RlcBgCIAEoBRIcChRjaG9zZW5fc2VydmVyX3JlZ2lvbhgD",
            "IAEoCUJXWlVnaXQudG9wZnJlZWdhbWVzLmNvbS9wYWNrYWdlcy91bml0eS1t",
            "b2R1bGVzLWRlbW8vc2VydmVyL21vZHVsZXMvYXV0aGVudGljYXRpb24vcHJv",
            "dG9zYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.V1.CreateAccountAdditionalArgs), global::Protos.V1.CreateAccountAdditionalArgs.Parser, new[]{ "Name", "TutorialStep", "ChosenServerRegion" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Example additional arguments for the metagame.authenticationHandler.createAccount route request.
  /// </summary>
  public sealed partial class CreateAccountAdditionalArgs : pb::IMessage<CreateAccountAdditionalArgs> {
    private static readonly pb::MessageParser<CreateAccountAdditionalArgs> _parser = new pb::MessageParser<CreateAccountAdditionalArgs>(() => new CreateAccountAdditionalArgs());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateAccountAdditionalArgs> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.V1.CreateAccountAdditionalArgsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateAccountAdditionalArgs() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateAccountAdditionalArgs(CreateAccountAdditionalArgs other) : this() {
      name_ = other.name_;
      tutorialStep_ = other.tutorialStep_;
      chosenServerRegion_ = other.chosenServerRegion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateAccountAdditionalArgs Clone() {
      return new CreateAccountAdditionalArgs(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tutorial_step" field.</summary>
    public const int TutorialStepFieldNumber = 2;
    private int tutorialStep_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TutorialStep {
      get { return tutorialStep_; }
      set {
        tutorialStep_ = value;
      }
    }

    /// <summary>Field number for the "chosen_server_region" field.</summary>
    public const int ChosenServerRegionFieldNumber = 3;
    private string chosenServerRegion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ChosenServerRegion {
      get { return chosenServerRegion_; }
      set {
        chosenServerRegion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateAccountAdditionalArgs);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateAccountAdditionalArgs other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (TutorialStep != other.TutorialStep) return false;
      if (ChosenServerRegion != other.ChosenServerRegion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (TutorialStep != 0) hash ^= TutorialStep.GetHashCode();
      if (ChosenServerRegion.Length != 0) hash ^= ChosenServerRegion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (TutorialStep != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TutorialStep);
      }
      if (ChosenServerRegion.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ChosenServerRegion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (TutorialStep != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TutorialStep);
      }
      if (ChosenServerRegion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChosenServerRegion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateAccountAdditionalArgs other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.TutorialStep != 0) {
        TutorialStep = other.TutorialStep;
      }
      if (other.ChosenServerRegion.Length != 0) {
        ChosenServerRegion = other.ChosenServerRegion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            TutorialStep = input.ReadInt32();
            break;
          }
          case 26: {
            ChosenServerRegion = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
